version: 43
imports:
- projectPath: OpenMandriva/Packages
  revision: mirroring
jobs:
- name: Build package(s)
  steps:
  - type: CheckoutStep
    name: Checkout code
    cloneCredential:
      type: DefaultCredential
    withLfs: true
    withSubmodules: true
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: Build
    runInContainer: true
    image: openmandriva/minimal:@param:version@
    interpreter:
      type: DefaultInterpreter
      commands: "set -e\n\nmount | grep onedev\nls -ld /onedev-build/workspace\nstat -c '%u %g %a %n' /onedev-build/workspace\n\ndnf --refresh --assumeyes upgrade\ndnf --assumeyes install bubblewrap wget curl rpmdevtools rpm-build\n\nfor spec in *.spec; do\n\tsudo dnf builddep --assumeyes \"$spec\"\ndone\n\t\n./rpm_download_source.sh\n./rpm_build.sh\n"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: Publish
    artifacts: '**/*.rpm'
    condition: SUCCESSFUL
    optional: false
  jobExecutor: builders-@script:omv-arch-to-onedev-arch@
  paramSpecs:
  - type: ChoiceParam
    name: arch
    allowMultiple: false
    allowEmpty: false
    choiceProvider:
      type: SpecifiedChoices
      choices:
      - value: aarch64
        color: '#0d87e9'
      - value: x86_64
        color: '#0d87e9'
      - value: znver1
        color: '#0d87e9'
  - type: ChoiceParam
    name: version
    allowMultiple: false
    allowEmpty: false
    choiceProvider:
      type: SpecifiedChoices
      choices:
      - value: cooker
        color: '#0d87e9'
      - value: rolling
        color: '#0d87e9'
      - value: rock
        color: '#0d87e9'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
